/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 map.glb --transform 
Files: map.glb [55.36MB] > /Users/totsukatomofumi/Desktop/medieval/map-transformed.glb [6.09MB] (89%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import mapModel from "./map-transformed.glb";

function Map(props) {
  const { nodes, materials } = useGLTF(mapModel);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials["brick1.001"]}
        position={[-34.14, 0, 0]}
        scale={[59.797, 21.777, 21.777]}
      />
      <mesh
        geometry={nodes.banner_0001.geometry}
        material={materials.wood_banner}
        position={[-53.543, 5.486, 2.049]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.banner_1001.geometry}
        material={materials.banner_flag}
        position={[-53.543, 5.486, 2.049]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.plant_01_0001.geometry}
        material={materials.plant}
        position={[-3.731, -0.034, 3.133]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_10002.geometry}
        material={materials["Material.004"]}
        position={[-41.185, 3.597, 2.679]}
        rotation={[0.698, 0, 0]}
        scale={[0.045, 0.054, 0.504]}
      />
      <mesh
        geometry={nodes.Object_4004.geometry}
        material={materials.Torch2_lambert1_AlbedoTransparency}
        position={[-22.326, 2.46, 1.89]}
        scale={139.333}
      />
      <mesh
        geometry={nodes.obj_house_1_material_planks_0001.geometry}
        material={materials["material_planks.002"]}
        position={[-6.144, 4.593, 6.442]}
        rotation={[-1.52, 0, Math.PI / 2]}
        scale={[0.091, 0.065, 0.999]}
      />
      <mesh
        geometry={nodes.obj_house_1_material_rocks_0001.geometry}
        material={materials["material_rocks.002"]}
        position={[-5.448, 0.522, 6.269]}
        rotation={[-1.52, 0, Math.PI / 2]}
        scale={[0.091, 0.065, 0.999]}
      />
      <mesh
        geometry={nodes.obj_house_1_material_roof_0001.geometry}
        material={materials["material_roof.002"]}
        position={[-6.366, 6.386, 6.437]}
        rotation={[-1.52, 0, Math.PI / 2]}
        scale={[0.091, 0.065, 0.999]}
      />
      <mesh
        geometry={nodes.obj_house_1_material_window_and_steel_0001.geometry}
        material={materials["material_window_and_steel.002"]}
        position={[-7.827, 7.892, 5.825]}
        rotation={[-1.52, 0, Math.PI / 2]}
        scale={[0.091, 0.065, 0.999]}
      />
      <mesh
        geometry={nodes.obj_house_1_material_wood_0001.geometry}
        material={materials["material_wood.002"]}
        position={[-6.017, 3.819, 6.362]}
        rotation={[-1.52, 0, Math.PI / 2]}
        scale={[0.091, 0.065, 0.999]}
      />
      <mesh
        geometry={nodes.porte_main_0.geometry}
        material={materials.main}
        position={[-55.866, 0, -0.003]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cube__0.geometry}
        material={materials["Scene_-_Root"]}
        position={[-23.188, 1.319, -3.029]}
        rotation={[-Math.PI / 2, 0, 0.059]}
      />
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Fire_lamp_2_0}
        position={[-24.208, -0.048, 0.128]}
        rotation={[0, -0.375, 0]}
        scale={1.397}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Glass_lamp_2_0}
        position={[-24.208, -0.048, 0.128]}
        rotation={[0, -0.375, 0]}
        scale={1.397}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Metal_lamp_2_0}
        position={[-24.208, -0.048, 0.128]}
        rotation={[0, -0.375, 0]}
        scale={1.397}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.Metal_wheel_2_0}
        position={[-24.208, -0.048, 0.128]}
        rotation={[0, -0.375, 0]}
        scale={1.397}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.Rope_2_0}
        position={[-24.208, -0.048, 0.128]}
        rotation={[0, -0.375, 0]}
        scale={1.397}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.Wood_cart_2_0}
        position={[-24.208, -0.048, 0.128]}
        rotation={[0, -0.375, 0]}
        scale={1.315}
      />
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.initialShadingGroup}
        position={[-2.341, 2.149, 3.652]}
        rotation={[0, 0, 0.149]}
        scale={2.422}
      />
      <mesh
        geometry={nodes.barrel_low_Material_0.geometry}
        material={materials.Material}
        position={[-2.797, 0, -2.579]}
        rotation={[-Math.PI / 2, 0, 1.247]}
        scale={0.323}
      />
      <mesh
        geometry={nodes.pCube104_lambert2_0.geometry}
        material={materials.lambert2}
        position={[-4.998, 0.682, -2.833]}
        scale={[0.11, 0.042, 0.077]}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.material}
        position={[-109.232, -0.31, -2.463]}
        rotation={[0, Math.PI / 2, 0]}
        scale={12.817}
      />
    </group>
  );
}

useGLTF.preload("/map-transformed.glb");

export default Map;
