/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 navmesh.glb --transform 
Files: navmesh.glb [4.1KB] > /Users/totsukatomofumi/Desktop/medieval/navmesh-transformed.glb [1.53KB] (63%)
*/

import React from "react";
import { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import navMeshModel from "./navmesh-transformed.glb";

const NavMesh = forwardRef(function NavMesh(props, ref) {
  const { nodes, materials } = useGLTF(navMeshModel);
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[-19.8, 0, -0.76]}
        scale={[1.623, 0.856, 1.314]}
      />
    </group>
  );
});

useGLTF.preload("/navmesh-transformed.glb");

export default NavMesh;
