/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 navmesh.glb --transform 
Files: navmesh.glb [4.1KB] > /Users/totsukatomofumi/Desktop/medieval/navmesh-transformed.glb [1.53KB] (63%)
*/

import React from "react";
import { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import navMeshModel from "./navmesh-transformed.glb";

const NavMesh = forwardRef(function NavMesh(props, ref) {
  const { nodes, materials } = useGLTF(navMeshModel);
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[1.8, 0, -0.7]}
        rotation={[0, 0.697, 0]}
      />
    </group>
  );
});

useGLTF.preload("/navmesh-transformed.glb");

export default NavMesh;
